version: '3'

services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672
  db:
    image: postgres:latest
  web:
    build: .
    command: bash -c "./manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq