# Generated by Django 2.0.3 on 2018-10-21 06:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filedownload',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 21, 6, 31, 15, 103366, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
