# Generated by Django 2.0.3 on 2018-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('hnm', models.FloatField(blank=True, null=True, verbose_name='H&M')),
                ('esprit', models.FloatField(blank=True, null=True, verbose_name='ESPRIT')),
                ('mns', models.FloatField(blank=True, null=True, verbose_name='M&S')),
                ('sainsbury', models.FloatField(blank=True, null=True, verbose_name='SAINSBURY')),
                ('inditex_indirect', models.FloatField(blank=True, null=True, verbose_name='INDITEX- (INDIRECT)')),
                ('inditex_direct', models.FloatField(blank=True, null=True, verbose_name='INDITEX- (DIRECT)')),
                ('tom_tailor', models.FloatField(blank=True, null=True, verbose_name='TOM TAILOR')),
                ('george', models.FloatField(blank=True, null=True, verbose_name='GEORGE')),
                ('other', models.FloatField(blank=True, null=True, verbose_name='OTHER')),
                ('best_seller', models.FloatField(blank=True, null=True, verbose_name='BEST SELLER')),
                ('varner', models.FloatField(blank=True, null=True, verbose_name='VARNER')),
                ('bestty_barclay', models.FloatField(blank=True, null=True, verbose_name='BESTTY BARCLAY')),
                ('carhartt', models.FloatField(blank=True, null=True, verbose_name='CARHARTT')),
                ('bonita', models.FloatField(blank=True, null=True, verbose_name='BONITA')),
                ('bench', models.FloatField(blank=True, null=True, verbose_name='BENCH')),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyer wise Confirmation (Pc)',
                'verbose_name_plural': 'Buyer wise Confirmation (Pcs)',
            },
        ),
    ]
