# Generated by Django 2.0.3 on 2018-11-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerWiseCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('confirmed', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerwise', to='confirmation.Buyer')),
            ],
            options={
                'verbose_name': 'Buyer wise Confirmation (Pc)',
                'verbose_name_plural': 'Buyer wise Confirmation (Pcs)',
            },
        ),
        migrations.DeleteModel(
            name='BuyerWise',
        ),
    ]
