# Generated by Django 2.0.3 on 2018-11-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0003_auto_20181125_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerwisetotal',
            name='buyer',
        ),
    ]
