# Generated by Django 2.0.3 on 2018-03-15 09:41

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_filedownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(upload_to=upload.models.uploads_directory_path),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='file_field',
            field=models.FileField(upload_to=upload.models.downloads_directory_path),
        ),
    ]
