# Generated by Django 2.0.3 on 2018-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180315_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='file_field',
            field=models.FileField(upload_to='downloads/'),
        ),
    ]
