# Generated by Django 2.0.3 on 2018-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GGPcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('confirmed_12', models.FloatField(blank=True, null=True, verbose_name='Confirmed 12/ 14gg')),
                ('reservations_12', models.FloatField(blank=True, null=True, verbose_name='Reservations 12/ 14gg')),
                ('projections_12', models.FloatField(blank=True, null=True, verbose_name='Projections 12/ 14gg')),
                ('open_12', models.FloatField(blank=True, null=True, verbose_name='Open 12/ 14gg')),
                ('confirmed_7', models.FloatField(blank=True, null=True, verbose_name='Confirmed 7gg')),
                ('reservations_7', models.FloatField(blank=True, null=True, verbose_name='Reservations 7gg')),
                ('projections_7', models.FloatField(blank=True, null=True, verbose_name='Projections 7gg')),
                ('open_7', models.FloatField(blank=True, null=True, verbose_name='Open 7gg')),
                ('confirmed_5', models.FloatField(blank=True, null=True, verbose_name='Confirmed 5gg')),
                ('reservations_5', models.FloatField(blank=True, null=True, verbose_name='Reservations 5gg')),
                ('projections_5', models.FloatField(blank=True, null=True, verbose_name='Projections 5gg')),
                ('open_5', models.FloatField(blank=True, null=True, verbose_name='Open 5gg')),
            ],
            options={
                'verbose_name': 'Capacity (GG wise Pc)',
                'verbose_name_plural': 'Capacity (GG wise Pcs)',
            },
        ),
        migrations.CreateModel(
            name='MachineDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('confirmed', models.FloatField(blank=True, null=True)),
                ('reservations', models.FloatField(blank=True, null=True)),
                ('projections', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('confirmed_perc', models.FloatField(blank=True, null=True, verbose_name='Confirmed %')),
                ('reservations_perc', models.FloatField(blank=True, null=True, verbose_name='Reservations %')),
                ('projections_perc', models.FloatField(blank=True, null=True, verbose_name='Projections %')),
                ('total_perc', models.FloatField(blank=True, null=True, verbose_name='Total %')),
            ],
            options={
                'verbose_name': 'Capacity Machine Day',
                'verbose_name_plural': 'Capacity Machine Days',
            },
        ),
        migrations.CreateModel(
            name='Pcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('confirmed', models.FloatField(blank=True, null=True)),
                ('reservations', models.FloatField(blank=True, null=True)),
                ('projections', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capacity (pc)',
                'verbose_name_plural': 'Capacity (pcs)',
            },
        ),
        migrations.CreateModel(
            name='SAH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Semi-Auto'), (1, 'Auto'), (2, 'Total')])),
                ('session', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')])),
                ('year', models.PositiveSmallIntegerField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('confirmed', models.FloatField(blank=True, null=True)),
                ('reservations', models.FloatField(blank=True, null=True)),
                ('projections', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('budget_v_plan', models.FloatField(blank=True, null=True, verbose_name='Budget Vs Plan')),
            ],
            options={
                'verbose_name': 'Capacity (SAH)',
                'verbose_name_plural': 'Capacity (SAH)',
            },
        ),
    ]
