# Generated by Django 2.0.3 on 2018-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sah',
            name='budget_epm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sah',
            name='budget_fob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sah',
            name='budget_va',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sah',
            name='confirmed_epm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sah',
            name='confirmed_fob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sah',
            name='confirmed_va',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
