# Generated by Django 2.0.3 on 2018-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0002_auto_20181024_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggpcs',
            name='session',
            field=models.IntegerField(choices=[(1, 'Jul'), (2, 'Aug'), (3, 'Sep'), (4, 'Oct'), (5, 'Nov'), (6, 'Dec'), (7, 'Jan'), (8, 'Feb'), (9, 'Mar'), (10, 'Apr'), (11, 'May'), (12, 'Jun'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')]),
        ),
        migrations.AlterField(
            model_name='machineday',
            name='session',
            field=models.IntegerField(choices=[(1, 'Jul'), (2, 'Aug'), (3, 'Sep'), (4, 'Oct'), (5, 'Nov'), (6, 'Dec'), (7, 'Jan'), (8, 'Feb'), (9, 'Mar'), (10, 'Apr'), (11, 'May'), (12, 'Jun'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')]),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='session',
            field=models.IntegerField(choices=[(1, 'Jul'), (2, 'Aug'), (3, 'Sep'), (4, 'Oct'), (5, 'Nov'), (6, 'Dec'), (7, 'Jan'), (8, 'Feb'), (9, 'Mar'), (10, 'Apr'), (11, 'May'), (12, 'Jun'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')]),
        ),
        migrations.AlterField(
            model_name='sah',
            name='session',
            field=models.IntegerField(choices=[(1, 'Jul'), (2, 'Aug'), (3, 'Sep'), (4, 'Oct'), (5, 'Nov'), (6, 'Dec'), (7, 'Jan'), (8, 'Feb'), (9, 'Mar'), (10, 'Apr'), (11, 'May'), (12, 'Jun'), (13, 'Q1'), (14, 'Q2'), (15, 'Q3'), (16, 'Q4'), (17, 'H1'), (18, 'H2')]),
        ),
    ]
